# WARNING - Generated by {fusen} from dev/ridlle_dev.Rmd: do not edit by hand

#' container_show  
#' 
#' Get an overview of accessible infos about all containers in RIDL
#'  Use https://docs.ckan.org/en/2.9/api/index.html#ckan.logic.action.get.organization_show  
#' @param id id or name of the container
#' @return a dataframe with container metadata
#' 
#' @export
#' @examples
#' # americasdataset <- container_show( id = "americas-regional-dataset")

container_show <- function(id) {
    r <-  ridl(action ="organization_show",
           include_datasets = TRUE,
           id = id) 
    
    res <- r$result %>% 
           dataset_tibblify()  
    
    return(res)
}

# container_show <- function(metadata) {
#       ridl(action ="organization_show",
#            type = "data-container",
#                     all_fields = TRUE,
#                     include_groups = TRUE ) -> r
#       r$result  |> length() -> res
#     
#       return(res)  }
