# WARNING - Generated by {fusen} from dev/ridlle_dev.Rmd: do not edit by hand


# usethis::use_rmarkdown_template(
#   template_name = "RIDL_Notebook",
#   template_dir = NULL,
#   template_description = "RIDL Dataset Exploration",
#   template_create_dir = TRUE
# )

#' riddle_notebook
#' 
#' Archive all crunching files in RIDL
#'
#' RIDL is UNHCR instance of a CKAN server and is accessible for UNHCR staff at
#' https://ridl.unhcr.org . It is designed to keep track and
#' document dataset within an organisation.
#'
#' You conveniently archive there your generated report and save
#' the work you did on a notebook: As you have been working on the data, you want
#' to keep track of it and save your work in a place where it can be useful for
#' other people and available for peer review and quality assessment.
#'
#'
#' The function saves within the  the RIDL container you used to get the data
#'  from the following resources:
#'   * the generated report
#'   * the source notebook
#'
#' The function behavior is the following -
#'   1. Get metadata from the RIDL dataset
#'   2. check if the resources to be uploaded is already shared based on the name
#'   3. if already there update, if not create
#'
#'  The function relies on   # install.packages("pak")
#'                           # pak::pkg_install("edouard-legoupil/riddle")
#'
#' @param ridl ridl container where the resources should be added
#' @param datafolder folder where the data used by the notebook are stored
#' @param namethisfile all files are archived based on the name of notebook you created.
#'     The function automatically get the name of the notebook where it is run from,
#'     using
#'      basename(rstudioapi::getSourceEditorContext()$path )
#'
#' @param visibility can be  "public" per default or set to private for obscure reasons..
#'
#' @importFrom riddle dataset_show resource_metadata resource_create resource_update
#'
#' @return nothing all analysis files are added as a resources
#'
#' @export
#' @examples
#' ## Time to archive your work once done!!
#' # used in the  RIDL_Notebook markdown template in the package
#' # if( params$publish == "yes"){
#' #   namethisfile = basename(rstudioapi::getSourceEditorContext()$path )  
#' #   riddle_notebook(ridl = params$ridl,
#' #             datafolder = params$datafolder, 
#' #             namethisfile =  namethisfile ,
#' #             visibility =  params$visibility ) }

# prefixer::import_from(fun = kobo_ridl)
riddle_notebook <- function(ridl,
                      datafolder, 
                      namethisfile,
                      visibility =  "public"){
  
  
  ### name of the file...
  # retrieving path from getSourceEditorContext()
  # using $ operator
  ## Enter below the name you used to save this file - without extension
  #    namethisfile <- rstudioapi::getSourceEditorContext()$path
  
  ### Remove file name extension
  name <-  substr(namethisfile,1, nchar(namethisfile) -4)
  #
  #    ## Now just the name of the file
  #    name1 <-   basename(rstudioapi::getSourceEditorContext()$path )
  #    ## Remove file name extension
  #   name <-  substr(name1,1, nchar(name1) -4)
  #
  #     ### Time to archive your work once done!!
  
  time <- format(Sys.Date(),  '%d%b%y')
  
  # ### Uncomment and Run this only once you have knitted your file in order to quickly upload this to RIDL -
  # install.packages("pak")
  # pak::pkg_install("edouard-legoupil/riddle")
  
  # First let's get the dataset metadata
  p <- riddle::dataset_show(ridl)
  list_of_resources <- p[["resources"]][[1]]
  #names(list_of_resources)
  #   "description"
  # "file_type"        questionnaire microdata report script
  # "format"
  # "id"    "name"
  # "type"                "url"
  # "visibility"
  # "identifiability"
  # "version"
  # "script_dependencies"
  # "script_instructions"
  #  "script_software"
  # "source_code_repo"
  
    ### 2.  Now publish the current notebook #######
  namenotebook = paste0("notebook_",    ridl)
  ### Check if the name is already in the resources
  if(namenotebook %in% list_of_resources$name) {
    ## get the resource id
    resourceid <- list_of_resources |>
      dplyr::filter ( name == namenotebook) |>
      dplyr::pull(id)
    ## get the new resource version
    curversion <- list_of_resources |>
      dplyr::filter ( name == namenotebook) |>
      dplyr::pull(version)
    metadataanalysisscript <- riddle::resource_metadata(type = "script",
                                                        url = paste0("notebook_",  name, ridl, time, ".Rmd"),
                                                        name = namenotebook,
                                                        description = paste0("Notebook for ",
                                                                               name,"_", ridl,"_", time,
                                                                             " report. Built using riddle "),
                                                        format = "rmd",
                                                        version = (as.integer(curversion) + 1),
                                                        visibility =  visibility,
                                           #             file_type = "other",
                                           file_type = "script",
                                                        script_dependencies= "riddle",
                                                        script_instructions= "Use the data 
                                           available within this RIDL dataset ",
                                                        script_software= "R",
                                                        source_code_repo= "https://edouard-legoupil.github.io/riddle",
                                           # Revise here based on the name from your crunching report
                                                        upload = httr::upload_file(here::here(namethisfile))
    )
    
    riddle::resource_update(id = resourceid,
                            res_metadata =  metadataanalysisscript)
  } else {
    metadataanalysisscript <- riddle::resource_metadata(type = "script",
                                                        url = paste0("notebook_",   name, ridl, time, ".Rmd"),
                                                        name = namenotebook,
                                                        description = paste0("Notebook for ",
                                                                               name,"_", ridl,"_", time,
                                                                             " report. Built using riddle "),
                                                        format = "Rmd",
                                                        visibility =  visibility,
                                            #            file_type = "other",
                                           file_type = "script",
                                                        script_dependencies= "riddle",
                                                        script_instructions= "Use the data 
                                           available within this RIDL dataset ",
                                                        script_software= "R",
                                                        source_code_repo= "https://edouard-legoupil.github.io/riddle",
                                                        ## Revise here based on the name from your crunching report
                                                        upload = httr::upload_file(here::here(namethisfile))
    )
    riddle::resource_create(package_id = p$id,
                            res_metadata = metadataanalysisscript)
  }
  
  ## 3.  and now the generated report - that should be hopefully already generated ####
  namereport = paste0("output_",  name, ridl )
  filext <- ".pdf" 
  ### Check if the name is already in the resources
  if(namereport %in% list_of_resources$name) {
    ## get the resource id
    resourceid <- list_of_resources |>
      dplyr::filter ( name == namereport) |>
      dplyr::pull(id)
    ## get the new resource version
    curversion <- list_of_resources |>
      dplyr::filter ( name == namereport) |>
      dplyr::pull(version)
    metadatareport <- riddle::resource_metadata(type = "attachment",
                                                url = paste0( name, ridl, time,".html"),
                                                name = paste0( name, ridl, time),
                                                description = paste0("Generated Report: ",
                                                                       name, " built on ", time,
                                                                     " using riddle package "),
                                                format = filext,
                                                version = (as.integer(curversion) + 1),
                                                visibility =  visibility,
                                                file_type = "report",
                                                ## Revise here based on the name from your crunching report
                                                upload = httr::upload_file(here::here(paste0(name,filext)))
    )
    
    riddle::resource_update(id = resourceid,
                            res_metadata = metadatareport)
  } else {
    metadatareport <- riddle::resource_metadata(type = "attachment",
                                                url = paste0( name, ridl, time,".pdf"),
                                                name = paste0( name, ridl, time),
                                                description = paste0("Generated Report: ",
                                                                       name, " built on ", time,
                                                                     " using ridlle package   "),
                                                format = filext,
                                                visibility =  visibility,
                                                file_type = "report",
                                                ## Revise here based on the name from your crunching report
                                                upload = httr::upload_file(here::here(paste0(name,filext)))
    )
    riddle::resource_create(package_id = p$id,
                            res_metadata = metadatareport)
  }
  
  
  ## Once all of it done, let's the user know about it...
  return( cat(paste0("Congrat! The Notebook", name, " together with linked output have been published on RIDL")))

  
  
    
}
